### ISSUE TITLE
adding a location

### ISSUE THREAD

**Issue by liedekef** [qTranslate-Team/events-made-easy-qtranslate-x#3]
When viewing and/or adding (not editing) a location, the page in both cases is 'page=eme-locations', however via the plugin this results in language buttons being added before the button 'add location' when viewing the list of locations. So either I should adapt EME for this, or the plugin should be able to take that into account, what do you think?

**Comment by johnclause** [comment]
Hi Franky, I changed the page attribute to "page=eme-locations&eme_admin_action=editlocation". Does this do what you need? It is in the latest: https://github.com/qTranslate-Team/events-made-easy-qtranslate-x/archive/master.zip I also changes file structure to follow same template as on other integrating plugins. Are we ready to publish it?

**Comment by johnclause** [comment]
Franky (@liedekef), would  you mind taking care of support for https://wordpress.org/plugins/events-made-easy-qtranslate-x/? I will add you to admin if you agree.

**Comment by liedekef** [comment]
No problem, you can add me.

**Comment by liedekef** [comment]
Btw: I think you forgot to add qeme-admin.php to the github version of events-made-easy-qtranslate-x

**Comment by johnclause** [comment]
Ouch, sorry, did now.

**Comment by johnclause** [comment]
How is it going Franky (@liedekef)? Do you need help? Don't your users bug you with this issue? Are they all right with different way? How far are we from the end? What are your plans? Best wishes, John.

**Comment by liedekef** [comment]
Well, between work, going to training with 2 dogs, family, several non-profit websites and wordpress plugins, there's sometimes a lack of time. For the moment I've been busy implementing payment gateways in EME and doing bugfixes in the 1 hour per day that can still be considered as free time (despite the fact that that hour is around midnight).
Now all that is hopefully finished again, so I should be able to work on this again. Don't forget: it will still all work (even without the changes in this plugin to translate EME admin pages), but people just need to enter the language tags themselves then (as they did before I guess). I'll try this evening ...

**Comment by liedekef** [comment]
This can be closed now

**Comment by johnclause** [comment]
Congratulations, Franky. I published it: https://wordpress.org/plugins/events-made-easy-qtranslate-x/
Please, update the description of https://wordpress.org/plugins/events-made-easy/ to advise use of this new plugin.

It would be the best if you check for qTranslate-X in the plugins tree on eme activation and suggest to install events-made-easy-qtranslate-x for integration. I will do the same in qTranslate-X.

**Comment by johnclause** [comment]
I added you as an admin, just in case I get hit by a car, you can continue without me ;)

**Comment by johnclause** [comment]
Franky (@liedekef), I added readme.md link and modified readme.txt to use GitHub compatible syntax.  Please, do not forget to subscribe to support thread and to watch it.

Since we are two authors now, we need to agree on the rules for updates. I suggest, to pull request as needed from both of us and if the other does not respond within 24 hours, go ahead and publish the change. Would this be ok? Any other ideas?

**Comment by liedekef** [comment]
Subscribe has been done.
I agree on the release method: most of the time it will be me that adds some lines anyway ...

**Comment by liedekef** [comment]
Concerning the check to suggest events-made-easy-qtranslate-x if qtranslate-x is installed: I'm interested to see how you do it on your end ...

**Comment by johnclause** [comment]
Hi Franky, I have done it in qtx (entry point is function qtranxf_admin_notices_plugin_integration), and then I realized that we should not duplicate it in two plugins, since this notice is only shown when two plugins are active at the same time.

If you wish to be fancy and user friendly, you may still add another notice in your plugin only when qTranslate-X is not installed or not active with a message like "Plugin Events Made Easy can be easily internationalized with plugin 'qTranslate-X' and plugin 'Events Made Easy & qTranslate-X'". Then it may help if you start with a copy of my function.
